[package]
name = "skillr"
description = "Lightweight skill rating library inspired by TrueSkill, OpenSkill, and the skillratings crate"
version = "0.1.2"
edition = "2024"
authors = ["rubenjr0"]
license = "AGPL-3.0-or-later"

[dependencies]
